attributes:
  multibackend:
    value: true
    label: 'Multi-backend enabled'
    description: 'Pure Storage will be used in a multi-backend environment'
    weight: 10
    type: "checkbox"
  pure_san_ip:
    value: ''
    label: 'Pure Storage Management IP (san_ip)'
    description: 'The hostname (or IP address) for the Pure Storage Management VIP.'
    weight: 20
    type: "text"
    regex:
      source: '\S'
      error: "IP field cannot be empty"
  pure_api:
    value: ''
    label: 'API Token for Pure Storage (pure_api_token)'
    description: 'Purity API token used to perform actions on the FlashArray.'
    weight: 30
    type: "text"
    regex:
      source: '\S'
      error: "API token field cannot be empty"
  pure_protocol:
    value: "iSCSI"
    values:
        - data: "iSCSI"
          label: "iSCSI"
          description: "Enables iSCSI protocol for block storage volumes"
    label: "Protocol for Pure Storage block access"
    description: 'Select block storage protocol for FlashArray.'
    weight: 60
    type: "radio"
  pure_chap:
    value: "true"
    values:
        - data: "true"
          label: "True"
          description: "Enables CHAP on iSCSI connections to FlashArray"
        - data: "false"
          label: "False"
          description: "Disables CHAP on iSCSI connections to FlashArray"
    label: "Pure Storage iSCSI CHAP (use_chap_auth)"
    description: 'Enable/Disable CHAP on iSCSI connections to the FlashArray.'
    weight: 60
    type: "radio"
  pure_multipath:
    value: "true"
    values:
        - data: "true"
          label: "True"
          description: "Enables multipathing for image transfers"
        - data: "false"
          label: "False"
          description: "Disables multipathing for image transfers"
    label: "Pure Storage Multipath for Image Transfers (use_multipath_for_image_xfer)"
    description: 'Enable/Disable multipathing for image transfers.'
    weight: 60
    type: "radio"
  pure_nova_multipath:
    value: "false"
    values:
        - data: "true"
          label: "True"
          description: "Enables multipathing for Nova compute servers"
        - data: "false"
          label: "False"
          description: "Disables multipathing for Nova compute servers"
    label: "Multipathing for Nova Compute servers (iscsi_use_multipath)"
    description: 'Enable/Disable multipathing for Nova compute servers.'
    weight: 60
    type: "radio"
